### ISSUE TITLE
Comment not associated with post

### ISSUE THREAD

**Issue by DuckArroyo** [DuckArroyo/just-tech-news#11]
CLI error while the server is running and I try to load localhost:3001
EagerLoadingError [SequelizeEagerLoadingError]: comment is not associated to post!
 at Function._getIncludedAssociation (/Users/duck/Documents/just-tech-news/node_modules/sequelize/lib/model.js:709:13)
    at Function._validateIncludedElement (/Users/duck/Documents/just-tech-news/node_modules/sequelize/lib/model.js:613:53)
    at /Users/duck/Documents/just-tech-news/node_modules/sequelize/lib/model.js:509:37
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/Users/duck/Documents/just-tech-news/node_modules/sequelize/lib/model.js:504:39)
    at Function.findAll (/Users/duck/Documents/just-tech-news/node_modules/sequelize/lib/model.js:1722:12)

**Comment by DuckArroyo** [comment]
resolved this issue. the wrong connection was being made in a sql table
